Cards
Hikari-Tanaka-pikka/hikarix-frontend-basic-last-assignment pull request #4
Opened 2023-02-23 03:53 UTC by Hikari-Tanaka-pikka

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

リンク
[](chromatic上の該当ページへのリンクを貼る)

2023-02-23 03:54 UTC, Hikari-Tanaka-pikka commented
https://github.com/shinonome-inc/hikarix-frontend-basic-last-assignment/pull/12

上記のPRの続きになります

2023-02-23 12:34 UTC, MinamiHotta commented
![image](https://user-images.githubusercontent.com/104500220/220907062-12846897-2366-40f4-adbe-eb841f8a15c9.png)
hover前に画像と文の隙間が空いてるので修正お願いします

2023-02-23 12:39 UTC, MinamiHotta commented
![image](https://user-images.githubusercontent.com/104500220/220908268-ed5bc868-c092-47fe-a321-1eedfdecfc4f.png)
どのボタンも、文字が縦方向で見ると中央でなく少し上気味になっているのが気になります

2023-03-01 14:34 UTC, Hikari-Tanaka-pikka commented
> ![image](https://user-images.githubusercontent.com/104500220/220908268-ed5bc868-c092-47fe-a321-1eedfdecfc4f.png) どのボタンも、文字が縦方向で見ると中央でなく少し上気味になっているのが気になります

対応しました!
bdd654ed0a2af6d2e1a00c03ca804b30cf73ae07

2023-03-01 14:34 UTC, Hikari-Tanaka-pikka commented
> ![image](https://user-images.githubusercontent.com/104500220/220908268-ed5bc868-c092-47fe-a321-1eedfdecfc4f.png) どのボタンも、文字が縦方向で見ると中央でなく少し上気味になっているのが気になります

対応しました!
bdd654ed0a2af6d2e1a00c03ca804b30cf73ae07

2023-03-01 14:34 UTC, Hikari-Tanaka-pikka commented
> ![image](https://user-images.githubusercontent.com/104500220/220907062-12846897-2366-40f4-adbe-eb841f8a15c9.png) hover前に画像と文の隙間が空いてるので修正お願いします

対応しました!
bdd654ed0a2af6d2e1a00c03ca804b30cf73ae07

2023-03-04 02:50 UTC, renyagi commented
<img width="1128" alt="スクリーンショット 2023-03-04 114905" src="https://user-images.githubusercontent.com/105191030/222872126-61a059d0-3183-4854-9565-695fa59a23e8.png">
small時のbutton-textの位置がおかしくなっているので修正お願いします

2023-03-04 02:55 UTC, renyagi commented
storybookとUI Testsが動作していない？ようです。
storybookに関してはChromatic / build (push)のRan choromauti何とかの中にあるURLから見れるので確認お願いします

2023-03-29 11:07 UTC, Hikari-Tanaka-pikka commented
> <img alt="スクリーンショット 2023-03-04 114905" width="1128" src="https://user-images.githubusercontent.com/105191030/222872126-61a059d0-3183-4854-9565-695fa59a23e8.png">
> 
> small時のbutton-textの位置がおかしくなっているので修正お願いします

対応しました!
bdd654ed0a2af6d2e1a00c03ca804b30cf73ae07

2023-03-29 11:08 UTC, Hikari-Tanaka-pikka commented
> storybookとUI Testsが動作していない？ようです。 storybookに関してはChromatic / build (push)のRan choromauti何とかの中にあるURLから見れるので確認お願いします

bdd654ed0a2af6d2e1a00c03ca804b30cf73ae07

2023-03-30 11:11 UTC, ssshun3 commented
[こちら](https://63f6dd30da259ac2af77c9d4-bvgunevvzx.chromatic.com/?path=/story/organisms-cards--cards)を確認してみたところ
![スクリーンショット 2023-03-30 200232](https://user-images.githubusercontent.com/110015394/228817504-3b0f22e4-575d-4006-9612-03ccf2958caa.png)
黒：bootstrapのcardにはdefaultでborder-radiusが設定されているのでそこの修正お願いします
また、以下二点の画面幅small時の修正がされていないように思えるのですがどうでしょうか？画像はcardのものですがcardsでも同じようになっています。
青：https://github.com/Hikari-Tanaka-pikka/hikarix-frontend-basic-last-assignment/pull/4#issuecomment-1441695622
オレンジ：https://github.com/Hikari-Tanaka-pikka/hikarix-frontend-basic-last-assignment/pull/4#issuecomment-1454347200

2023-04-01 11:30 UTC, Hikari-Tanaka-pikka commented
> [こちら](https://63f6dd30da259ac2af77c9d4-bvgunevvzx.chromatic.com/?path=/story/organisms-cards--cards)で確認してみました。 ![スクリーンショット 2023-03-30 200232](https://user-images.githubusercontent.com/110015394/228817504-3b0f22e4-575d-4006-9612-03ccf2958caa.png) 黒：bootstrapのcardにはdefaultでborder-radiusが設定されているのでそこの修正お願いします また、以下二点の画面幅small時の修正がされていないように思えるのですがどうでしょうか？画像はcardのものですがcardsでも同じようになっています。 青：[#4 (comment)](https://github.com/Hikari-Tanaka-pikka/hikarix-frontend-basic-last-assignment/pull/4#issuecomment-1441695622) オレンジ：[#4 (comment)](https://github.com/Hikari-Tanaka-pikka/hikarix-frontend-basic-last-assignment/pull/4#issuecomment-1454347200)

対応しました!

c17aaa6eda0387dd93298fa81207e83de5f441b5

2023-04-02 15:17 UTC, caramelribon reviewed
画像幅がsmのときで、hoverしたときに画像が縮小される感じになっているので、修正お願いします！！
↓hover前
![スクリーンショット 2023-04-03 0 16 00](https://user-images.githubusercontent.com/91133956/229362110-7a4a6f8d-b0f1-4180-bb7c-74dec57c4d18.png)

↓hover後
![スクリーンショット 2023-04-03 0 12 41](https://user-images.githubusercontent.com/91133956/229362129-9dcc33a8-2e38-47df-af7c-f96a6c0e258f.png)

2023-04-15 16:14 UTC, Hikari-Tanaka-pikka commented
> 画像幅がsmのときで、hoverしたときに画像が縮小される感じになっているので、修正お願いします！！ sm以下のときは画像の変化は必要ないです！
> 
> ↓hover前 ![スクリーンショット 2023-04-03 0 16 00](https://user-images.githubusercontent.com/91133956/229362110-7a4a6f8d-b0f1-4180-bb7c-74dec57c4d18.png)
> 
> ↓hover後 ![スクリーンショット 2023-04-03 0 12 41](https://user-images.githubusercontent.com/91133956/229362129-9dcc33a8-2e38-47df-af7c-f96a6c0e258f.png)

対応しました!

0112139b2ac073f5204c83cc4898d8e232b4706c

2023-04-18 00:57 UTC, KEISUKE0293 reviewed
とりあえずはOKです！

2023-04-18 00:57 UTC, KEISUKE0293 commented on src/components/organisms/cards/cards.html
> +        </figure>
![image](https://user-images.githubusercontent.com/88794030/232640920-7112ab5d-2015-413a-9974-5fd14a53bdb9.png)
細かいですが、上部と下部の間に若干の余白があります。
こちらはfigma内でもある場合とない場合があるので、2次レビュアーの方の判断に委ねます！

2023-04-18 02:48 UTC, higashiji2000 requested changes
不要ファイルの削除だけお願いします！”

2023-04-18 02:48 UTC, higashiji2000 commented on src/img/image 2.png
この画像はおそらく使っていないと思うので削除お願いします！

2023-04-18 02:48 UTC, higashiji2000 commented on src/img/image 3.png
こちらも同様に削除お願いします。

2023-04-18 02:48 UTC, higashiji2000 commented on git.sh
> +git push
めっちゃいいですね！！

2023-04-18 02:48 UTC, higashiji2000 commented on src/components/organisms/cards/cards.html
> +        </figure>
自分の環境では確認できませんでした、、
ご指摘の通りfigmaでも曖昧な状態なので、一旦このままで大丈夫です！

2023-04-18 12:32 UTC, Hikari-Tanaka-pikka commented on src/img/image 3.png
@higashiji2000 

対応しました!
b8413ceec24f20633457198bd476ef85a29f5c8f

2023-04-18 12:32 UTC, Hikari-Tanaka-pikka commented on src/img/image 2.png
@higashiji2000 

対応しました!
b8413ceec24f20633457198bd476ef85a29f5c8f

2023-04-20 16:16 UTC, higashiji2000 approved these changes
LGTMです📮

2023-05-01 13:26 UTC, merged